rolling_window: true

width: 10
height: 10
resolution: 0.05

update_frequency: 8.0
publish_frequency: 5.0

plugins:
  - {name: obstacles_laser,           type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}