rolling_window: true

width: 10
height: 10
resolution: 0.1

update_frequency: 8.0
publish_frequency: 5.0

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}