recovery_behaviour_enabled: true
clearing_rotation_allowed: false # No rotation when stuck

controller_frequency: 8.0 # Controller will execute every x hz 
controller_patience: 3.0 

planner_patience: 1.0 

NavfnROS:
  allow_unknown: true # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  default_tolerance: 0.1 # A tolerance on the goal point for the planner.


MpcLocalPlannerROS:
  
  ## Robot settings
  robot:
    type: "simple_car"
    simple_car:
      wheelbase: 0.5120
      front_wheel_driving: False
      
      max_vel_x: 0.5
      min_vel_x: 0.0
      max_vel_x_backwards: 0.2

      max_vel_y: 0.0
      min_vel_y: 0.0

      max_vel_theta: 0.5
      max_steering_angle: 1.0

      acc_lim_x: 0.2 # deactive bounds with zero
      dec_lim_x: 0.2 # deactive bounds with zero
      
      max_steering_rate: 0.5 # deactive bounds with zero

  ## Footprint model for collision avoidance
  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    type: "polygon"
    vertices: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
    is_footprint_dynamic: False

  ## Collision avoidance
  collision_avoidance:
    costmap_obstacles_behind_robot_dist: 1.5
    cutoff_dist: 2.5 
    enable_dynamic_obstacles: True #look it up on the wiki
    force_inclusion_dist: 0.5
    include_costmap_obstacles: True
    min_obstacle_dist: 0.1
    
  ## Planning grid 
  grid:
    collocation_method: "forward_differences"
    cost_integration_method: "left_sum"
    dt_ref: 0.3
    grid_size_ref: 20
    type: "fd_grid"
    variable_grid:
      enable: True  
      min_dt: 0.0;
      max_dt: 10.0;
      grid_adaptation:
        enable: True
        dt_hyst_ratio: 0.1
        min_grid_size: 2
        max_grid_size: 50
    warm_start: True
    xf_fixed: [True, True, True]

  ## Planning options
  planning:
    objective:
      type: "minimum_time" # minimum_time requires grid/variable_grid/enable=True and grid/xf_fixed set properly
      quadratic_form:
        state_weights: [2.0, 2.0, 2.0]
        control_weights: [1.0, 1.0]
        integral_form: False
      minimum_time_via_points:
        position_weight: 10.5
        orientation_weight: 0.0
        via_points_ordered: False
    terminal_cost:
      type: "none" # can be "none"
      quadratic:
        final_state_weights: [2.0, 2.0, 2.0]
    terminal_constraint:
      type: "none" # can be "none"
      l2_ball:
        weight_matrix: [1.0, 1.0, 1.0]
        radius: 5

  ## Controller options
  controller:
    allow_init_with_backward_motion: True #TODO add back sensor
    force_reinit_new_goal_angular: 1.57
    force_reinit_new_goal_dist: 1.0
    force_reinit_num_steps: 0
    global_plan_overwrite_orientation: True
    global_plan_prune_distance: 1.0
    global_plan_viapoint_sep: 5.5
    max_global_plan_lookahead_dist: 1.5 
    outer_ocp_iterations: 2
    prefer_x_feedback: False
    publish_ocp_results: False
    xy_goal_tolerance: 0.3
    yaw_goal_tolerance: 0.3
    
  ## Solver settings
  solver:
    type: "ipopt"
    ipopt:
      iterations: 10
      max_cpu_time: -1.0
      ipopt_numeric_options:
        tol: 1e-4
      ipopt_string_options:
        linear_solver: "mumps" 
        hessian_approximation: "limited-memory" # exact/limited-memory, WARNING 'exact' does currently not work well with the carlike model
    lsq_lm:
      iterations: 10
      weight_init_eq: 2
      weight_init_ineq: 2
      weight_init_bounds: 4
      weight_adapt_factor_eq: 1.5
      weight_adapt_factor_ineq: 1.5
      weight_adapt_factor_bounds: 1.5
      weight_adapt_max_eq: 500
      weight_adapt_max_ineq: 500
      weight_adapt_max_bounds: 500
