topics:
- name    : joy
  topic   : /husky1/joy_teleop/cmd_vel
  timeout : 0.5
  priority: 10
- name    : kb
  topic   : /husky1/kb_teleop/cmd_vel
  timeout : 0.5
  priority: 9
- name    : interactive_marker
  topic   : /husky1/twist_marker_server/cmd_vel
  timeout : 0.5
  priority: 8
- name    : external
  topic   : /husky1/cmd_vel
  timeout : 0.5
  priority: 1
locks:
- name    : e_stop
  topic   : /husky1/e_stop
  timeout : 0.0
  priority: 255