map_type: costmap
footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
#footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 5.0

resolution: 0.01

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    enabled:               true
    voxel_decay:           0.75     #seconds if linear, e^n if exponential
    decay_model:           0      #0=linear, 1=exponential, -1=persistent
    voxel_size:            0.05   #meters
    track_unknown_space:   true   #default space is unknown
    observation_persistence: 0.0  #seconds
    max_obstacle_height:   2.0    #meters
    unknown_threshold:     15     #voxel height
    mark_threshold:        0      #voxel height
    update_footprint_enabled: true
    combination_method:    1      #1=max, 0=override
    obstacle_range:        10.0   #meters
    origin_z:              0.0    #meters
    publish_voxel_map:     false   # default off
    transform_tolerance:   0.2    # seconds
    mapping_mode:          false  # default off, saves map not for navigation
    map_save_duration:     60 
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: font/scan, inf_is_valid: true}

inflation:
    inflation_radius: 0.80
    cost_scaling_factor: 1.8

